### ISSUE TITLE
"Verify endpoint" doesn't check what version of code it's hitting

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm#129]
we need a way to check which version is deployed. 

I don't know what this is, but we need one

**Comment by johnsonr** [comment]
This requires cooperation in the deployed service.
Spring Boot can be used to support this.

**Comment by johnsonr** [comment]
Consider proper secure solution for Spring and Node

**Comment by johnsonr** [comment]
This is a deployment goal issue not an SDM issue
