### ISSUE TITLE
We should be using GitHub deployment events

### ISSUE THREAD

**Issue by claymccoy** [atomist/sdm#155]
I know they aren't in our model yet. I assume there are plans to introduce it?
Even before then, this looks useful enough to consider using it directly.
https://developer.github.com/v3/repos/deployments/

It fits in well with our flow. It has a list of commit status contexts that should be passing, which aligns with our gating ideas. There is a transient and production environment to promote to. There is a legit json payload that can be attached to it.  A deployment is immutable, but it can have statuses attached to show progress that are similar to commit statuses. The status has multiple urls, including a specific log url.

This could really simplify things for us!

**Comment by johnsonr** [comment]
We might want to surface this events but we have our own model and Atomist should initiate the deployment
