### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#223]
Load testing and any necessary optimization.

Goal: *To ensure we can scale to run on hundreds of repos, and understand what will need to be done to handle thousands*

Specifically:

- Proving we can do code updates across hundreds of repos. At least understanding challenges of _thousands_ of repos.
- Sense of the number of projects we can accommodate concurrent events requiring cloning with

**Comment by johnsonr** [comment]
Is this fixed?

**Comment by cdupuis** [comment]
I think we can close this as much as we can possibly test it.
