### ISSUE TITLE
Jenkins-based demo option

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#235]
Should be easy to switch from in-automation-node to Jenkins build

**Comment by ddgenome** [comment]
https://www.linux.com/blog/learn/chapter/Intro-to-Kubernetes/2017/5/set-cicd-pipeline-kubernetes-part-1-overview

**Comment by johnsonr** [comment]
Should we consider running a Jenkins server in a docker container to show we can integrate with on prem Jenkins.

**Comment by ddgenome** [comment]
The blog I linked above walls through running Jenkins and a Docker registry inside Kubernetes.

**Comment by johnsonr** [comment]
Could we run it within Minikube?

Goals:

- Show we can integrate with people's existing real world build servers
- Convenient setup so that it's not hard to prep a machine for a demo, and it's not hard for users to replicate that
- Make it easy to see Jenkins logs or UIs during demos, as waiting without any feedback looks back
- Access to Jenkins UI to show builds and logs

**Comment by johnsonr** [comment]
Add Jenkins integration sample to README. Do we need a plugin?

**Comment by johnsonr** [comment]
Issue moved to atomist/sdm-ecosystem#9
