### ISSUE TITLE
Add feedback during long-running builds run within automation client

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#252]
Currently we just get a blinking dot. That's fine, and as good as we get with Travis/whatever, but we have an opportunity if we are actually running the build to provide a much better experience.

We could write back to Slack, or perhaps update the build status shown Slack.

For example, we could show progress in the test suite, or something else to indicate we're running.

**Comment by jrday** [comment]
We could push the build log output to a snipped and update it as the build/tests progress. It stays collapsed in Slack unless you want to expand and see the progress. Takes up a bit of real estate though.

Could also use a horizontal progress bar indicating how long it has been running so you see not just that it started, but how long it has been running. Possibly project it as a 100% progress bar if we know the prior build time.

**Comment by cdupuis** [comment]
I think this is interesting. I have an idea I want to explore.

**Comment by johnsonr** [comment]
This is done now
