### ISSUE TITLE
Let goal implementations choose preconditions

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm#272]
## problem statement
Some deploys need to go when the build finishes. (like node to CF, there's no artifact)
Some deploys need to go when an artifact exists.

Therefore, the implementation of a goal (as determined by the push) must be determined before the goal runs. It is needed to set up the events that might trigger it, and the 

## Current state:
there are DeployRules and also conditional builders. These are examples of different implementations applying to the same goal. In each case (separately), the rules are applied on invocation to determine which one to run. However, the triggering conditions for deploy and build are constant in a goal set.

## Desired state:
any goal can have multiple implementations. The implementation is chosen by PushRule at the time of Goal Setting. The implementation name gets stored on the SdmGoal. Each implementation (instance of a class) knows its precondition: both "am I satisfied?" and "what event handlers are needed?"
In event handlers that might trigger goal execution, the implementation is looked up by name, and it is asked whether preconditions are satisfied. If so, its execution is run.

## Plan
I think first I'll change the current functionalUnitForGoal to work as the trivial case, exactly one implementation per goal, for any push. Then move deployTriggers into the more general case of a goal with multiple implementations. Make them work for the cases we need. (then our driving problem case is solved)
Then builders should move into this model too.

### alternatives considered
there are some beautiful things we could do with graphql assembly and general subscriptions, if we had that stuff implemented.

we could have waited until goal-execution time to determine implementation (again based on the push), creating event handlers for all possibilities. but then we couldn't tell people ahead of time what is planned, and people love that stuff. (it's still possible to change the plan by updating goals)

### additional benefits
we can also attach log interpreters to implementations, helping with general-invocation, specific-implementation of log parsing. Like, provide one and you get retry, logs to slack, etc.

someday, extensibility: Rod has the idea of a GoalPack: people can provide goals along with implementation sets, complete with PushRules that say whether they can apply.

**Comment by johnsonr** [comment]
This is now possible in the rule DSL
