### ISSUE TITLE
Make a better workaround for not getting org token on custom events

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm#279]
Currently it's grabbing the token from GITHUB_TOKEN as a workaround for automation-api#392, but that doesn't work for other configuration mechanisms.

Get it from the configuration; ask @ddgenome how to do this.

Check its scopes and output a nice error if it doesn't have repo scope. It'll need it for creating GH statuses.

**Comment by cdupuis** [comment]
We should now use the `@Value` annotation.
