### ISSUE TITLE
Move SdmGoal event ingestion to a global automation

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm#287]
These need to be in one place, and it needs to be durable, so that the events can be queried by multiple automations.

Also move the CopyGoalToGitHubStatus there, because that also needs to be in one place. Have it skip any goals with an empty externalKey.

**Comment by cdupuis** [comment]
`SdmGoal` got moved to a global automation. That part is done.

Moving the `CopyGoalToGitHubStatus` to the global automation makes sense too.
