### ISSUE TITLE
Move high-level Goal handlers to sdm-automation

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm#345]
CopyGoalToStatus
RequestDownstreamOnSuccess
FailDownstreamOnFailure

... these apply to goals generally, we need exactly one, in the global automation.

**Comment by cdupuis** [comment]
I assume it is the following two: 
```
RequestDownstreamOnSuccess
FailDownstreamOnFailure
```

**Comment by cdupuis** [comment]
Now that those handlers are specific to a certain SDM this not needed/desired any more.
