### ISSUE TITLE
Fix npm audit warnings

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#383]
See output of `npm audit`

**Comment by lievendoclo** [comment]
We're using https://github.com/IBM-Cloud/cf-nodejs-client as one of the dependencies which is responsible for the bulk of the audit issues through its transitive dependencies. We could try to force the transitive dependencies, but the cf-client project hasn't been updated for over 2 years.

**Comment by cdupuis** [comment]
How is bringing this in?

**Comment by lievendoclo** [comment]
Apparently the cf-client dependency can be removed without issues. However, the latest version of NPM itself is causing 2 low severity issues through transitive dependencies, all related to lodash, on which we depend with a version that is compliant with npm audit
