### ISSUE TITLE
Un-fail skipped statuses when a retried deploy succeeds

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm#45]
when 3-deploy fails, FailDownstreamOnFailedStatus marks 4-endpoint and 5-verify as failed with a "Skipping" description. 
When the deploy is retried and succeeds, those statuses need to go back to pending. (actually endpoint gets successful anyway, since it reacts to the deploy. But verify stays failed)

Actually, right now, we could probably just set the Verify handler to run if its status is currently failed.

The general issue is still true; i'll make a separate one for that.

**Comment by johnsonr** [comment]
Obsolete
