### ISSUE TITLE
Refine checkstyle comments

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm#46]
to get these to be pretty, they need:
- ~the links to work~
- also show the line in Slack
- autofixing
- a collapse/expand button

**Comment by johnsonr** [comment]
Local directory prefix is not correctly being removed. This is the link issue.

I'm not sure that displaying them in the Slack is the right thing to do. Perhaps a link on a status? A collapse/expand button would make them useful in Slack.

Checkstyle doesn't provide auto fixing, so we'd need to. This is out of scope for RI, as far as Checkstyle goes. We could use some of our own reviewers (like the "Phil" reviewers) if we want auto fix.

**Comment by johnsonr** [comment]
Significant interest in Checkstyle integration at QCon. Worth prioritizing

**Comment by johnsonr** [comment]
Issue moved to atomist/sdm-pack-checkstyle#4
