### ISSUE TITLE
ExecuteGoalResult should not extend HandlerResult

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#469]
It feels like we're confusing the wire-level result from `automation-client` with the pure TypeScript API of SDM.

Should we just allow throwing an error on failure, with normal return constituting success? That would enable consistent error handling.

**Comment by cdupuis** [comment]
Return type changed to `Promise<void | ExecuteGoalResult>` and removed the hard dependency on `HandlerResult`.
