### ISSUE TITLE
Rename newRepoWithCodeListeners to firstPushListeners

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#480]
Keep existing method and deprecate till 1.0.0.

**Comment by jessitron** [comment]
this impacts core, local, sdm-pack-spring, sdm-pack-cloudfoundry, and sample-sdm.

might as well change it now, and we don't want to deprecate because it's time for 1.0.0

**Comment by cdupuis** [comment]
Isn't that completed?
