### ISSUE TITLE
Push tests for adding a goal implementation are not run

### ISSUE THREAD

**Issue by claymccoy** [atomist/sdm#490]
After talking to @cdupuis, this looks like a contract change to `findImplementationBySdmGoal()` to return a promise since running the push tests will make this function async.
https://github.com/atomist/sdm/blob/fc9099909b7fa814a6581dc1b397d5ad16affc19/src/api-helper/goal/SdmGoalImplementationMapperImpl.ts#L41

This is needed to attach different implementations to goals in atomist-sdm for Node vs Maven projects.

**Comment by cdupuis** [comment]
I have the base implementation for this done. Need some testing and then I raise a PR.

**Comment by cdupuis** [comment]
Fixed #493
