### ISSUE TITLE
Getting stuck when following sdm installation instructions

### ISSUE THREAD

**Issue by jhuiting** [atomist/sdm#491]
I've followed instructions on the page `https://atomist.com/developer.html`. At the end of step 2, after creating the `Spring` SDM I'm getting the error ` Could not connect to the bootstrap SDM at http://${HOSTNAME}:2900` where HOSTNAME is the name of my local PC. 

Can you provide me with some clue why this doesn't work?

**Comment by cdupuis** [comment]
Hey @jhuiting, I'm pretty sure you are hitting atomist/sdm-local/issues#160. To verify can you please make sure your hostname resolves via dns? If you're on a Mac, try adding the HOSTNAME to your `/etc/hosts` file.

We fixed the root cause of that and will hopefully have a new release out soon.

**Comment by jhuiting** [comment]
Thanks a lot for the quick reply @cdupuis, I'm on a Mac and adding the HOSTNAME to /etc/hosts fixed the problem!

**Comment by cdupuis** [comment]
Thanks @jhuiting for letting us know. Happy to assist with any further questions or issues.
