### ISSUE TITLE
Add ability to run through entire GoalSets without causing side effects

### ISSUE THREAD

**Issue by kipz** [atomist/sdm#551]
Discussed with @cdupuis today as a way for Atomist to regression test the backend (performance and to some extent functionally) with current good SDM's, without causing side-effects.

The proposal is to have a new mode that can be enabled via config that puts each goal in to one of three duration buckets (short, medium or long running) to simulate and end to end SDM run. 

It should also be possible to incrementally add more sophisticated mocks in the future for side effecting things like deployments, docker image publication etc.

**Comment by kipz** [comment]
cc @slimslenderslacks

**Comment by slimslenderslacks** [comment]
good, thanks for adding this.  As shown by the last week, we really really need this.

**Comment by cdupuis** [comment]
This is implemented now. Will do some more tests. Should be ready tomorrow.
