### ISSUE TITLE
Inform PR author if there are conflicts with target branch

### ISSUE THREAD

**Issue by kipz** [atomist/sdm#569]
I get burned by this a bit, and it would be solved by full PR builds too I guess, but I'd rather be told quickly if my PR has merge conflicts with the target branch, either because the target has changed, or if the PR was conflicting when raised

**Comment by johnsonr** [comment]
At what point would you like to be informed? On each push or when raising a PR (when GitHub will tell you).

This feels like it should be a in git workflow pack, rather than core, so long as we have enough to implement it, and I think we do.

**Comment by cdupuis** [comment]
Yeah, I’ll address this once I start to move the GitHub stuff out of lifecycle into an sdm pack.

**Comment by kipz** [comment]
> At what point would you like to be informed? On each push or when raising a PR (when GitHub will tell you).

Well, we could add this incrementally, and see how it goes. It mostly happens to me when I raise the PR via the bot, but pushes would be handy too!

**Comment by cdupuis** [comment]
Issue moved to atomist/sdm-pack-issue#18
