### ISSUE TITLE
Support for limiting number of concurrent GoalSets for a branch

### ISSUE THREAD

**Issue by kipz** [atomist/sdm#571]
Sometimes we end up doing many pushes in quick succession to a branch. For libraries, this rarely causes any issues, but for our services, this _can_ cause:

1. use of a lot of our SDM resources
2. Incorrect ordering of deployment (if an earlier build takes longer for example)

Travis has this feature to auto-cancel earlier running builds, and we used it a lot.

**Comment by cdupuis** [comment]
Can you provide an example of a use case you are trying to achieve?

**Comment by cdupuis** [comment]
I wonder if that could be a goal that stops previous goalsets on the same branch and sdm.

**Comment by kipz** [comment]
That's a good idea - set them the SdmGoal's to skipped?

**Comment by cdupuis** [comment]
Yeah, to `canceled`. We have that state already but don’t use it yet.
