### ISSUE TITLE
Deprecate paramsMaker

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm#667]

**Comment by lievendoclo** [comment]
So you mean deprecating the annotation based parameters?

**Comment by cdupuis** [comment]
> So you mean deprecating the annotation based parameters?

Not sure if I want to deprecate the actual decorators as they are being used actively by old style automation clients. But deprecate the `paramsMaker` property of `CommandHandlerRegistration` and `GeneratorRegistration` etc might be a start.

**Comment by johnsonr** [comment]
Yes. We should discourage the annotation style as the newer parameters model is more composable and less magical. It now enforces that parameter definitions match the relevant interface, which eliminates the last reason to use decorators.

**Comment by lievendoclo** [comment]
Ok agreed, but I'd change the documentation to have the parameterDefinition variables typed, i.e.:

```
const helloWorldParametersDefinition: ParametersDefinition = {
        name: { description: "name",
            required: true,
            pattern: /.*/ },
        location: {},
    };
```

That way people have code completion in IDEs.
