### ISSUE TITLE
Allow Generator Message Customization

### ISSUE THREAD

**Issue by ipcrm** [atomist/sdm#671]
https://github.com/atomist/sdm/blob/bce83e98e186f8e9bd7bafc3bada0dbd12198c22/lib/api-helper/command/generator/generatorCommand.ts#L155-L159

^^Allow supplying custom messages to display on successful/unsuccessful project creation.

**Comment by cdupuis** [comment]
Current plan is to use a special message id on options so that consumers can filter message to re-write with an `AutomationEventListener.messageSending` hook.
