### ISSUE TITLE
Fail Goals after timeout 

### ISSUE THREAD

**Issue by ipcrm** [atomist/sdm#681]
When a new goal is created, if the SDM that created it disconnects that goal will indefinitely stay in a running state.  This can cause issues if the consumer of the SDMs services is not aware the SDM is down and should issue a `reset goals`.  These goals should be set to failed after a timeout period.

**Comment by cdupuis** [comment]
This has now been added to the `goalStateSupport` extension part that is part of `sdm-core`.
