### ISSUE TITLE
Session ID being used as Bearer in Authorization header

### ISSUE THREAD

**Issue by neilprosser** [atomist/sdm#689]
We've seen the `SdmGoalById` using the Session ID in the Authorization header. This was previously supported but we'd like to move to using API Keys instead.

**Comment by cdupuis** [comment]
The framework doesn’t allow that any more. Likely an outdated SDM somewhere.

**Comment by cdupuis** [comment]
Looks like some still uses the jwt. 

https://github.com/atomist/sdm-core/blob/master/lib/handlers/events/delivery/goals/GoalAutomationEventListener.ts#L63

We should deprecate that property from Registration api.

**Comment by cdupuis** [comment]
Related issue atomist/automation-client#491 created
