### ISSUE TITLE
Identity tokens in CommandHandlerRequest maps

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/sdm#702]
The existing `source` map is augmented by an _optional_ `identity` map.  

```json
{
    "source": {
        "identity": {
            "token": "xxxxxxx"
        }
    }
}
```

The first workspace where you'll start to see identity maps in the source will be the atomist prod workspace using google auth.  And the netflix workspace will start to support these id tokens once we've migrated their workspace to use meecham.

**Comment by cdupuis** [comment]
Issue moved to atomist/automation-client#497
