### ISSUE TITLE
Switch to using github octokit client rather than axios

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#71]

**Comment by cdupuis** [comment]
Latest integration is at https://github.com/atomist/lifecycle-automation/blob/master/src/handlers/command/github/gitHubApi.ts

I've had some issues when upgrading from npm module `github` to `@octokit/rest` but that link above link should work.

**Comment by johnsonr** [comment]
This is pretty unimportant

**Comment by johnsonr** [comment]
Wondering if this is valid, given the work we've had to do with customers on Axios proxying.

**Comment by ddgenome** [comment]
This is definitely something we will have to consider as we migh migrate things over to use the Http client abstraction.

**Comment by johnsonr** [comment]
I don't think this is a real issue any more.
