### ISSUE TITLE
Wrong issue linked in PR rendering

### ISSUE THREAD

**Issue by kipz** [atomist/sdm#716]
The commit message references `#atomisthq/pochta#309`, but the rendering includes that _and_ `#atomisthq/neo4j-ingester#309` - which is the current mapped repo.

![Screenshot_20190425_114524](https://user-images.githubusercontent.com/1865026/56730769-a2ed0e00-6750-11e9-8995-9186febb3b1c.png)

**Comment by cdupuis** [comment]
Issue moved to atomist/lifecycle-automation#280
