### ISSUE TITLE
Automatically redact HTTP authentication info in chat messages

### ISSUE THREAD

**Issue by ipcrm** [atomist/sdm#718]
Potentially using `AutomationEventListener.messageSending`, apply a regex to detect anything that looks like `http[s]://user:pass@host[:port]/.*` and replace it with `http[s]://user:[REDACTED]@host[:port]/.*` in the chat message.  This will prevent any authentication info from ever getting sent to a chat platform if the creator of that message is not parsing it themselves.

**Comment by cdupuis** [comment]
Issue moved to atomist/automation-client#526
