### ISSUE TITLE
Code Inspection: Tslint on nortissej/autofix-location

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm#751]
### deprecation

- [`lib/api/machine/WellKnownGoals.ts:48`](https://github.com/atomist/sdm/blob/02974f1a6b1f4aa1aea939bf36c2f411e6b26e1e/lib/api/machine/WellKnownGoals.ts#L48): _(error)_ Fingerprint is deprecated: use fingerprintSupport with a PushImpact goal
- [`test/api/dsl/goalContribution.test.ts:59`](https://github.com/atomist/sdm/blob/02974f1a6b1f4aa1aea939bf36c2f411e6b26e1e/test/api/dsl/goalContribution.test.ts#L59): _(error)_ Fingerprint is deprecated: use fingerprintSupport with a PushImpact goal
- [`test/api/goal/Goals.test.ts:36`](https://github.com/atomist/sdm/blob/02974f1a6b1f4aa1aea939bf36c2f411e6b26e1e/test/api/goal/Goals.test.ts#L36): _(error)_ Fingerprint is deprecated: use fingerprintSupport with a PushImpact goal

[atomist:code-inspection:nortissej/autofix-location=@atomist/atomist-sdm]

**Comment by neilprosser** [comment]
Issue closed because branch `nortissej/autofix-location` was deleted.
