### ISSUE TITLE
Code Inspection: npm audit on nortissej/autofix-location

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm#752]
### marked:>=0.3.14 <0.6.2

- _(warn)_ [Regular Expression Denial of Service](https://npmjs.com/advisories/812) _Upgrade to version 0.6.2 or later._ 
  - `marked:0.4.0`: 
    - `typedoc>marked`

[atomist:code-inspection:nortissej/autofix-location=@atomist/atomist-sdm]

**Comment by neilprosser** [comment]
Issue closed because branch `nortissej/autofix-location` was deleted.
