### ISSUE TITLE
Out of the box container goal definitions

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm#784]
We need to build up a catalogue of container goal definitions. Currently we got:

- https://github.com/atomist/maven-goal
- https://github.com/atomist/npm-goal
- https://github.com/atomist/docker-goal
- https://github.com/atomist/version-goal

We should add:

- [ ] Kaniko docker build
- [ ] Leinigen build & test
- [x] Gradle build & test
- [ ] Kubernetes deploy using our KubernetesDeploy goal

**Comment by lievendoclo** [comment]
Added Gradle goal: https://github.com/atomist/gradle-goal

**Comment by lievendoclo** [comment]
Added .NET Core: https://github.com/atomist/dotnetcore-goal

**Comment by ddgenome** [comment]
Other priorities and issues are driving the creation of the container goals now.
