### ISSUE TITLE
Provide goal/action execution result to project listeners?

### ISSUE THREAD

**Issue by XertroV** [atomist/sdm#833]
From what I can tell [ProjectListenerInvokingProjectLoader.ts](https://github.com/atomist/sdm/blob/817dd3b571c1cb4dabdbb0e29d8e2c4137d5c4ff/lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts) is where project listeners are invoked.

It might be useful to pass the result of the action to project listeners. Looks like the variable is already in scope, too. (I ran into this writing a listener to do before/after logic to support github checks for each goal; couldn't get master of sdm-pack-rcca-github working, also not sure if current master even does that)

PR for it feels easy and quick so I'm happy to write that, but wanted to check first if there was a better way to do it (currently playing with GoalExecutionListener instead)

**Comment by XertroV** [comment]
So I got my thing working (only issue is some url shenanigans).

I realised, though, that I might not have been looking in the right place before. In the GoalExecutionListener the result is at `gi.goalEvent.result`, so if the same thing is possible with the ProjectListener please close this issue. I don't _think_ it is, because with execution listeners we're passed a `GoalExecutionListenerInvocation` not a `GoalInvocation`.

**Comment by cdupuis** [comment]
@XertroV the project listeners are only intended for operation that should occur before or after working with `Project` instances returned by the `ProjectLoader`. It appears as if the extension point you are looking for is the `GoalExecutionListener` (as you found).

Reading your comment, I'm unsure if there's still something to do here?

**Comment by XertroV** [comment]
@cdupuis yup - I've gathered a bit more digging into sdm-pack-build WRT to 2.0; particularly via the depreacted Artifact stuff and projectListeners being referenced there. Makes more sense now. (not sure if you actually planed to upgrade that, but it was the way I found to do the thing 😃 )

Yep, I think we're good. Ta!
