### ISSUE TITLE
Documentation question: sdm vs goal vs skill

### ISSUE THREAD

**Issue by bbl** [atomist/sdm#843]
Hello! I was interested in the atomist platform and concepts you're using. 

I'm trying to understand what is the difference between the following concepts: **sdm, skill, goal**. I tried to search through the documentation on the atomist website, but there are no clear definitions of these terms.

Thanks in advance!

**Comment by cdupuis** [comment]
Hi @bbl, this is a good question. Let me try to explain the differences:

A _goal_ is a step in your delivery process that gets planned and fulfilled by an _SDM_. This is repository is the home of the SDM framework. An SDM is a Node.JS process written in TypeScript that you can take and deploy to cloud runtimes or your own datacenter. It then connects to our backend and listens to incoming events like Git pushes or chat commands. 

A _Skill_ is an event-driven automation that can be written in any language (as function or Docker image) and can be triggered by various event sources. Skills are being hosted and managed by the Atomist platform. 

Let me know if that is helpful?
