### ISSUE TITLE
Commit-image relationship should be commit-images

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm#96]
The 1:1 relationship commit:image is deprecated. All subscriptions and queries should use the 1:N relationship commit:images.

For example https://github.com/atomist/github-sdm/blob/81c6c0408f81f6dfaebfa70cbc3b95374eb81c70/graphql/subscription/OnAnySuccessStatus.graphql#L29

**Comment by johnsonr** [comment]
Is this still incorrect?
